### ISSUE TITLE
document when to use /reset

### ISSUE THREAD

**Issue by xaur** [companyzero/zkc#107]
I discovered the reset command via `/help` but `/help reset` does not tell me when I should use it.

Using 0.1.1, perhaps it was fixed since then.

**Comment by marcopeereboom** [comment]
Fixed in #123

**Comment by xaur** [comment]
@marcopeereboom tested in v0.3.0, `/help reset` text improved but still does not tell when I should use it. It is rumored one uses reset when he sees ratchet-related errors.

**Comment by xaur** [comment]
@marcopeereboom shall I make a new issue for explaining when to use `/reset`?
